name: Build Site
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
      - name: Install Dependencies
        working-directory: ./src
        run: |
          gem install bundler
          bundle install
      - name: Get Secrets (Development)
        if: github.ref != 'refs/heads/master' && !contains(github.ref, '/rl-')
        run: |
          echo "::set-env name=azureAppInsightsKey::${{ secrets.AZURE_APP_INSIGHTS_KEY_DEV }}"
      - name: Get Secrets (Production)
        if: github.ref == 'refs/heads/master' || contains(github.ref, '/rl-')
        run: |
          echo "::set-env name=azureAppInsightsKey::${{ secrets.AZURE_APP_INSIGHTS_KEY_PROD }}"
      - name: Apply Secrets
        working-directory: ./src
        run: |
          find . -type f -exec sed -i "s/{{secrets.azureAppInsightsKey}}/$azureAppInsightsKey/g" {} +
      - name: Build Site
        run: |
          make build
      - name: Upload Build Artefact
        uses: actions/upload-artifact@v2
        with:
          name: bwhazel-web-site
          path: dist